import {axes,createState,selected,selectMajor,validate,canHandoff,begin,finish,invalidate,scenario} from './model.mjs';
const state=createState(), root=document.querySelector('#workspace');
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n===null?'Chưa có dữ liệu':String(n);
const announce=text=>document.querySelector('#status').textContent=text;
const groupNames=['Đã có minh chứng','Đang phát triển','Cần bổ sung'];
let returnFocus=null;
function notice(title,body,error=false){return `<div class="notice ${error?'error':''}" ${error?'role="alert"':''}><strong>${title}</strong><p>${body}</p></div>`;}
function table(m){return `<details class="numbers" ${matchMedia('(forced-colors: active)').matches?'open':''}><summary>Xem bảng số liệu</summary><div class="table-scroll" tabindex="0" role="region" aria-label="Bảng sáu trục có thể cuộn ngang"><table><caption>${m.name}: hồ sơ và benchmark minh họa, thang 0–10. Taxonomy chờ D03.</caption><thead><tr><th scope="col">Trục</th><th scope="col">Hồ sơ mẫu</th><th scope="col">Benchmark mẫu</th><th scope="col">Chênh lệch</th></tr></thead><tbody>${axes.map((a,i)=>`<tr><th scope="row">${a[1]}</th><td>${fmt(m.current[i])}</td><td>${fmt(m.benchmark[i])}</td><td>${m.current[i]===null||m.benchmark[i]===null?'Không tính':Math.round((m.benchmark[i]-m.current[i])*10)/10}</td></tr>`).join('')}</tbody></table></div><p class="source">Nguồn: fixture thiết kế. Chênh lệch = benchmark − hồ sơ mẫu; không phải readiness. Chưa xác minh nguồn benchmark.</p></details>`;}
function skills(m){return `<section class="skills" aria-labelledby="skills-title"><h3 id="skills-title">Kỹ năng tiêu biểu</h3><p>Phân nhóm minh họa, không xác nhận năng lực của bạn.</p>${state.mode==='partial'?notice('Chưa có minh chứng học tập','Sở thích không thay thế điểm hoặc kỹ năng. Bổ sung hồ sơ để có dữ liệu đối chiếu.'):groupNames.map((g,i)=>`<section class="skill-group group-${i}"><h4 class="group-label"><span>${g}</span><span>${m.skills.filter(s=>s.group===i).length}</span></h4>${m.skills.filter(s=>s.group===i).map(s=>`<div class="skill"><strong>${s.name}</strong><p>${s.reason}</p><details><summary>Nguồn minh chứng ${s.name}</summary><p>${s.source}. Nhóm có sẵn trong fixture; policy phân nhóm chờ D04.</p></details></div>`).join('')||'<p class="small">Không có kỹ năng trong nhóm này theo dữ liệu hiện có.</p>'}</section>`).join('')}</section>`;}
function render(focusId){
  const global={
    'no-session':['Chưa có kết quả','Bắt đầu từ hồ sơ và sở thích. Không tự khôi phục hoặc tạo dữ liệu cho bạn.'],
    loading:['Đang phân tích dữ liệu mẫu','Kịch bản chờ dành cho review. Chưa có điểm để hiển thị.'],
    empty:['Chưa có gợi ý trong kết quả này','Bạn có thể sửa thông tin và phân tích lại. Điều này không có nghĩa là không có ngành phù hợp.'],
    invalid:['Dữ liệu chưa hợp lệ','Một trục nằm ngoài thang 0–10. Radar và handoff đã bị chặn; không tự sửa điểm.'],
    error:['Chưa kết nối được','Bản mô phỏng đang ở trạng thái lỗi. Thử lại khi bạn sẵn sàng.'],
    timeout:['Đã hết thời gian chờ','Yêu cầu cũ không còn được dùng. Bạn có thể thử lại; không có kết quả mẫu tự thay thế.'],
    rate:['Chưa thể gửi lại yêu cầu','Máy chủ mô phỏng không cung cấp Retry-After. Không hiển thị đồng hồ chờ giả.']
  }[state.mode];
  if(global){root.innerHTML=`<section class="empty-state" ${['invalid','error','timeout','rate'].includes(state.mode)?'role="alert"':''}><h2>${global[0]}</h2><p>${global[1]}</p><div class="actions"><a href="../../ingestion/prototype/">Về hồ sơ &amp; sở thích</a><button class="primary" id="retry">${state.mode==='no-session'?'Xem dữ liệu minh họa':state.mode==='loading'?'Hoàn tất mô phỏng':'Thử lại mô phỏng'}</button></div></section>`; document.querySelector('#retry').onclick=()=>{scenario(state,'success');render();announce('Đã mở kết quả minh họa.');};return;}
  const m=selected(state), unavailable=state.mode==='unavailable'&&state.selected==='web';
  if(!m||!validate(state.items)){scenario(state,'invalid');render();return;}
  root.innerHTML=`<aside><fieldset class="major-list"><legend>Chọn chuyên ngành để xem chi tiết</legend><div class="rail-intro"><h3>Chọn ngành để khám phá</h3><p>Tối đa 3 gợi ý, chọn 1 để xem chi tiết.</p></div>${state.items.map(item=>`<label class="major ${item.id===state.selected?'selected':''}" for="major-${item.id}"><input id="major-${item.id}" type="radio" name="major" value="${item.id}" ${item.id===state.selected?'checked':''} ${state.pending?'disabled':''}><span><strong>${item.name}</strong><span class="meta"><span class="score">${item.score}% <span class="sr-only">điểm minh họa</span></span>${item.id===state.selected?'<span class="chosen">Đang chọn</span>':''}</span></span></label>`).join('')}<p class="rail-note">Điểm Match là chỉ số tính toán mẫu, không phải xác suất thành công. Thứ tự và cách tính chờ D02.</p></fieldset></aside>
  <section class="detail" aria-labelledby="major-title" aria-busy="${state.pending}"><div class="detail-head"><h2 id="major-title">${m.name}</h2><p>${m.description}</p><p class="source">Dữ liệu tổng hợp cho thiết kế · Không phải phân tích hồ sơ thật</p></div>
  ${state.mode==='stale'?notice('Kết quả cần phân tích lại','Hồ sơ hoặc sở thích đã đổi. Dữ liệu dưới đây là bản cũ; không thể dùng để tạo lộ trình.'):''}
  ${!state.context?notice('Chưa đủ ngữ cảnh cho lộ trình','Thiếu học kỳ và môn đã học. Không tự gán GPA hoặc học kỳ mẫu. Cách bổ sung ngữ cảnh chờ D06 / XD-01.'):''}
  ${unavailable?notice('Ngành này chưa có chi tiết','Vẫn giữ lựa chọn Fullstack Web Engineer. Không lấy radar hoặc kỹ năng từ ngành khác. Hợp đồng dữ liệu chờ D03.'): `<div class="analysis-grid"><section class="radar-region" aria-labelledby="radar-title"><h3 id="radar-title">Hồ sơ năng lực</h3><p class="chart-caption">Thang 0–10 · Số liệu mẫu</p>${state.mode==='partial'?notice('Chưa có điểm năng lực','Chỉ hiển thị benchmark minh họa. Không chuyển sở thích thành điểm năng lực.'):''}<canvas id="radar" width="560" height="460" role="img" aria-label="Radar sáu trục của ${m.name}. Bảng số liệu đầy đủ ngay bên dưới."></canvas><div class="legend"><span class="current">Nét liền: hồ sơ mẫu</span><span class="benchmark">Nét đứt: benchmark mẫu</span></div><p class="source">Benchmark minh họa, chưa xác minh nguồn.</p><div class="axis-controls" aria-label="Đọc chi tiết từng trục">${axes.map((a,i)=>`<button data-axis="${i}">${a[1]}</button>`).join('')}</div></section>${skills(m)}</div>${table(m)}`}
  ${state.mode==='roadmap-error'?notice('Chưa tạo được lộ trình mẫu','Lựa chọn và dữ liệu đối chiếu vẫn được giữ. Bạn có thể thử lại.',true):''}
  ${state.handoff?notice('Đã chuẩn bị bàn giao mẫu',`Ngành ${m.name}. Đây là bản xem dữ liệu bàn giao, chưa kết nối Advisor.`)+`<details open><summary>Xem dữ liệu bàn giao</summary><pre>${escape(JSON.stringify(state.handoff,null,2))}</pre></details>`:''}
  <div class="actions"><a href="../../ingestion/prototype/">Sửa hồ sơ</a><button class="primary" id="handoff" ${!canHandoff(state)?'disabled':''}>${state.pending?'Đang chuẩn bị bàn giao…':state.mode==='roadmap-error'?'Thử lại lộ trình mẫu':'Xem học phần gợi ý'}</button>${state.pending?'<button id="cancel">Hủy chờ</button>':''}${state.mode==='stale'?'<button id="reanalyze">Phân tích lại mẫu</button>':''}</div><p class="action-note">${state.pending?'Đang giữ nguyên ngành đã chọn. Có thể hủy chờ.':state.handoff?'Bản minh họa chỉ chuẩn bị bàn giao, không tạo học phần thật.':canHandoff(state)?'Xem trước dữ liệu bàn giao sang Advisor, chưa gọi API.':'Cần dữ liệu và ngữ cảnh hợp lệ trước khi tiếp tục.'}</p></section>`;
  document.querySelectorAll('[name="major"]').forEach(el=>el.addEventListener('change',()=>{if(selectMajor(state,el.value)){render(el.id);announce(`Đã chọn ${selected(state).name}, chi tiết đã cập nhật.`);}}));
  document.querySelectorAll('[data-axis]').forEach(el=>el.onclick=()=>{const i=Number(el.dataset.axis);returnFocus=el;document.querySelector('#axis-title').textContent=axes[i][1];document.querySelector('#axis-body').innerHTML=`<p>Hồ sơ mẫu: ${fmt(m.current[i])}<br>Benchmark mẫu: ${fmt(m.benchmark[i])}</p><p>Thang 0–10. Nguồn: fixture thiết kế, chưa xác minh benchmark.</p>`;document.querySelector('#axis-dialog').showModal();});
  document.querySelector('#handoff').onclick=()=>{const token=begin(state);if(!token)return;render('cancel');announce('Đang chuẩn bị bàn giao mẫu.');setTimeout(()=>{if(finish(state,token)){render('handoff');announce(`Đã chuẩn bị bàn giao mẫu cho ${selected(state).name}.`);}},1200);};
  document.querySelector('#cancel')?.addEventListener('click',()=>{state.request++;state.pending=false;render('handoff');announce('Đã hủy chờ. Dữ liệu và ngành đã chọn được giữ.');});
  document.querySelector('#reanalyze')?.addEventListener('click',()=>{scenario(state,'success');render('major-ai');announce('Đã mở snapshot minh họa mới.');});
  const controls=document.querySelector('.axis-controls');
  if(controls){const disclosure=document.createElement('details');disclosure.className='axis-disclosure';const summary=document.createElement('summary');summary.textContent='Đọc chi tiết từng trục';controls.before(disclosure);disclosure.append(summary,controls);}
  draw(m); if(focusId)document.getElementById(focusId)?.focus();
}
function draw(m){
  const c=document.querySelector('#radar');if(!c)return;
  const ctx=c.getContext('2d'),w=560,h=460,cx=280,cy=222,r=156;
  const pos=(i,v)=>[cx+Math.sin(i*Math.PI/3)*r*v/10,cy-Math.cos(i*Math.PI/3)*r*v/10];
  const polygon=(values,color,dash=[],fill=false)=>{ctx.beginPath();values.forEach((v,i)=>{const [x,y]=pos(i,v);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.closePath();ctx.strokeStyle=color;ctx.setLineDash(dash);ctx.lineWidth=2;if(fill){ctx.fillStyle='#a5b4fc20';ctx.fill();}ctx.stroke();ctx.setLineDash([]);};
  ctx.clearRect(0,0,w,h);[2,4,6,8,10].forEach(v=>polygon(Array(6).fill(v),'#334155'));ctx.font='21px "Segoe UI", sans-serif';ctx.fillStyle='#b8c3d4';ctx.textAlign='left';[2,4,6,8,10].forEach(v=>ctx.fillText(String(v),cx+7,cy-r*v/10+5));
  axes.forEach((a,i)=>{const [x,y]=pos(i,10);ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(x,y);ctx.strokeStyle='#334155';ctx.lineWidth=1;ctx.stroke();const [lx,ly]=pos(i,12.6);ctx.textAlign='center';const parts=a[1].split(' '),split=Math.ceil(parts.length/2);ctx.fillStyle='#b8c3d4';ctx.fillText(parts.slice(0,split).join(' '),lx,ly-3);ctx.fillText(parts.slice(split).join(' '),lx,ly+17);});
  if(m.benchmark.every(v=>v!==null))polygon(m.benchmark,'#b8c3d4',[7,6]);
  if(m.current.every(v=>v!==null)){polygon(m.current,'#a5b4fc',[],true);m.current.forEach((v,i)=>{const[x,y]=pos(i,v);ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fillStyle='#a5b4fc';ctx.fill();});}
}
document.querySelector('#close-axis').onclick=()=>document.querySelector('#axis-dialog').close();
document.querySelector('#axis-dialog').addEventListener('close',()=>returnFocus?.focus());
document.querySelector('#apply').onclick=()=>{scenario(state,document.querySelector('#scenario').value);render();announce('Đã mở kịch bản review.');};
document.querySelector('#invalidate').onclick=()=>{invalidate(state);render();announce('Hồ sơ đã đổi. Kết quả cũ không thể bàn giao.');};
document.querySelector('#nav-roadmap').onclick=()=>{document.querySelector('#handoff')?.scrollIntoView({block:'center'});announce('Chọn ngành có đủ dữ liệu rồi dùng nút Xem học phần gợi ý. Bản này chưa kết nối Advisor.');};
render();
